/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me. support and admin can read the internal /users routes.
 * OpenAPI spec version: 0.4.0
 */
import type {
  HealthCheckResponse,
  User
} from './model';

import { sdkFetch } from '../runtime';

/**
 * @summary Users service health check
 */
export type healthControllerGetHealthResponse200 = {
  data: HealthCheckResponse
  status: 200
}
    
export type healthControllerGetHealthResponseSuccess = (healthControllerGetHealthResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetHealthResponse = (healthControllerGetHealthResponseSuccess)

export const getHealthControllerGetHealthUrl = () => {


  

  return `/health`
}

export const healthControllerGetHealth = async ( options?: RequestInit): Promise<healthControllerGetHealthResponse> => {
  
  return sdkFetch<healthControllerGetHealthResponse>(getHealthControllerGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Customer self-service route. The target user is always resolved from the JWT sub claim.
 * @summary Return the authenticated user profile
 */
export type usersControllerGetMeResponse200 = {
  data: User
  status: 200
}

export type usersControllerGetMeResponse401 = {
  data: void
  status: 401
}

export type usersControllerGetMeResponse404 = {
  data: void
  status: 404
}
    
export type usersControllerGetMeResponseSuccess = (usersControllerGetMeResponse200) & {
  headers: Headers;
};
export type usersControllerGetMeResponseError = (usersControllerGetMeResponse401 | usersControllerGetMeResponse404) & {
  headers: Headers;
};

export type usersControllerGetMeResponse = (usersControllerGetMeResponseSuccess | usersControllerGetMeResponseError)

export const getUsersControllerGetMeUrl = () => {


  

  return `/me`
}

export const usersControllerGetMe = async ( options?: RequestInit): Promise<usersControllerGetMeResponse> => {
  
  return sdkFetch<usersControllerGetMeResponse>(getUsersControllerGetMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Read-only internal route for support and admin personas.
 * @summary Return the internal users list
 */
export type usersControllerGetUsersResponse200 = {
  data: User[]
  status: 200
}

export type usersControllerGetUsersResponse401 = {
  data: void
  status: 401
}

export type usersControllerGetUsersResponse403 = {
  data: void
  status: 403
}
    
export type usersControllerGetUsersResponseSuccess = (usersControllerGetUsersResponse200) & {
  headers: Headers;
};
export type usersControllerGetUsersResponseError = (usersControllerGetUsersResponse401 | usersControllerGetUsersResponse403) & {
  headers: Headers;
};

export type usersControllerGetUsersResponse = (usersControllerGetUsersResponseSuccess | usersControllerGetUsersResponseError)

export const getUsersControllerGetUsersUrl = () => {


  

  return `/users`
}

export const usersControllerGetUsers = async ( options?: RequestInit): Promise<usersControllerGetUsersResponse> => {
  
  return sdkFetch<usersControllerGetUsersResponse>(getUsersControllerGetUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Read-only internal route for support and admin personas. Customer self-access is intentionally exposed only through /me.
 * @summary Return an internal user by userId
 */
export type usersControllerGetUserResponse200 = {
  data: User
  status: 200
}

export type usersControllerGetUserResponse401 = {
  data: void
  status: 401
}

export type usersControllerGetUserResponse403 = {
  data: void
  status: 403
}

export type usersControllerGetUserResponse404 = {
  data: void
  status: 404
}
    
export type usersControllerGetUserResponseSuccess = (usersControllerGetUserResponse200) & {
  headers: Headers;
};
export type usersControllerGetUserResponseError = (usersControllerGetUserResponse401 | usersControllerGetUserResponse403 | usersControllerGetUserResponse404) & {
  headers: Headers;
};

export type usersControllerGetUserResponse = (usersControllerGetUserResponseSuccess | usersControllerGetUserResponseError)

export const getUsersControllerGetUserUrl = (userId: number,) => {


  

  return `/users/${userId}`
}

export const usersControllerGetUser = async (userId: number, options?: RequestInit): Promise<usersControllerGetUserResponse> => {
  
  return sdkFetch<usersControllerGetUserResponse>(getUsersControllerGetUserUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



