/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.1.0
 */
import type {
  HealthCheckResponse,
  User
} from './model';


/**
 * @summary Users service health check
 */
export type healthControllerGetHealthResponse200 = {
  data: HealthCheckResponse
  status: 200
}
    
export type healthControllerGetHealthResponseSuccess = (healthControllerGetHealthResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetHealthResponse = (healthControllerGetHealthResponseSuccess)

export const getHealthControllerGetHealthUrl = () => {


  

  return `http://localhost:3001/health`
}

export const healthControllerGetHealth = async ( options?: RequestInit): Promise<healthControllerGetHealthResponse> => {
  
  const res = await fetch(getHealthControllerGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthControllerGetHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthControllerGetHealthResponse
}



/**
 * @summary Return a list of all users
 */
export type usersControllerGetUsersResponse200 = {
  data: User[]
  status: 200
}
    
export type usersControllerGetUsersResponseSuccess = (usersControllerGetUsersResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetUsersResponse = (usersControllerGetUsersResponseSuccess)

export const getUsersControllerGetUsersUrl = () => {


  

  return `http://localhost:3001/users`
}

export const usersControllerGetUsers = async ( options?: RequestInit): Promise<usersControllerGetUsersResponse> => {
  
  const res = await fetch(getUsersControllerGetUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerGetUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerGetUsersResponse
}



/**
 * @summary Return details of a specific user
 */
export type usersControllerGetUserResponse200 = {
  data: User
  status: 200
}
    
export type usersControllerGetUserResponseSuccess = (usersControllerGetUserResponse200) & {
  headers: Headers;
};
;

export type usersControllerGetUserResponse = (usersControllerGetUserResponseSuccess)

export const getUsersControllerGetUserUrl = (id: number,) => {


  

  return `http://localhost:3001/users/${id}`
}

export const usersControllerGetUser = async (id: number, options?: RequestInit): Promise<usersControllerGetUserResponse> => {
  
  const res = await fetch(getUsersControllerGetUserUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerGetUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerGetUserResponse
}



