/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Payments Service
 * Payments service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me/payments. support and admin can read internal /payments routes and user payment lookups.
 * OpenAPI spec version: 0.4.0
 */
import type {
  HealthCheckResponse,
  Payment
} from './model';

import { sdkFetch } from '../runtime';

/**
 * @summary Payments service health check
 */
export type healthControllerGetHealthResponse200 = {
  data: HealthCheckResponse
  status: 200
}
    
export type healthControllerGetHealthResponseSuccess = (healthControllerGetHealthResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetHealthResponse = (healthControllerGetHealthResponseSuccess)

export const getHealthControllerGetHealthUrl = () => {


  

  return `/health`
}

export const healthControllerGetHealth = async ( options?: RequestInit): Promise<healthControllerGetHealthResponse> => {
  
  return sdkFetch<healthControllerGetHealthResponse>(getHealthControllerGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Customer self-service route. The service resolves ownership from the JWT sub claim instead of trusting caller-supplied user ids.
 * @summary Return the authenticated user payments
 */
export type paymentsControllerGetMyPaymentsResponse200 = {
  data: Payment[]
  status: 200
}

export type paymentsControllerGetMyPaymentsResponse401 = {
  data: void
  status: 401
}
    
export type paymentsControllerGetMyPaymentsResponseSuccess = (paymentsControllerGetMyPaymentsResponse200) & {
  headers: Headers;
};
export type paymentsControllerGetMyPaymentsResponseError = (paymentsControllerGetMyPaymentsResponse401) & {
  headers: Headers;
};

export type paymentsControllerGetMyPaymentsResponse = (paymentsControllerGetMyPaymentsResponseSuccess | paymentsControllerGetMyPaymentsResponseError)

export const getPaymentsControllerGetMyPaymentsUrl = () => {


  

  return `/me/payments`
}

export const paymentsControllerGetMyPayments = async ( options?: RequestInit): Promise<paymentsControllerGetMyPaymentsResponse> => {
  
  return sdkFetch<paymentsControllerGetMyPaymentsResponse>(getPaymentsControllerGetMyPaymentsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Read-only internal route for support and admin personas.
 * @summary Return the internal payments list
 */
export type paymentsControllerGetPaymentsResponse200 = {
  data: Payment[]
  status: 200
}

export type paymentsControllerGetPaymentsResponse401 = {
  data: void
  status: 401
}

export type paymentsControllerGetPaymentsResponse403 = {
  data: void
  status: 403
}
    
export type paymentsControllerGetPaymentsResponseSuccess = (paymentsControllerGetPaymentsResponse200) & {
  headers: Headers;
};
export type paymentsControllerGetPaymentsResponseError = (paymentsControllerGetPaymentsResponse401 | paymentsControllerGetPaymentsResponse403) & {
  headers: Headers;
};

export type paymentsControllerGetPaymentsResponse = (paymentsControllerGetPaymentsResponseSuccess | paymentsControllerGetPaymentsResponseError)

export const getPaymentsControllerGetPaymentsUrl = () => {


  

  return `/payments`
}

export const paymentsControllerGetPayments = async ( options?: RequestInit): Promise<paymentsControllerGetPaymentsResponse> => {
  
  return sdkFetch<paymentsControllerGetPaymentsResponse>(getPaymentsControllerGetPaymentsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Read-only internal route for support and admin personas. The route identifies a payment resource by paymentId; it is not a user-payment shortcut.
 * @summary Return an internal payment by paymentId
 */
export type paymentsControllerGetPaymentResponse200 = {
  data: Payment
  status: 200
}

export type paymentsControllerGetPaymentResponse401 = {
  data: void
  status: 401
}

export type paymentsControllerGetPaymentResponse403 = {
  data: void
  status: 403
}

export type paymentsControllerGetPaymentResponse404 = {
  data: void
  status: 404
}
    
export type paymentsControllerGetPaymentResponseSuccess = (paymentsControllerGetPaymentResponse200) & {
  headers: Headers;
};
export type paymentsControllerGetPaymentResponseError = (paymentsControllerGetPaymentResponse401 | paymentsControllerGetPaymentResponse403 | paymentsControllerGetPaymentResponse404) & {
  headers: Headers;
};

export type paymentsControllerGetPaymentResponse = (paymentsControllerGetPaymentResponseSuccess | paymentsControllerGetPaymentResponseError)

export const getPaymentsControllerGetPaymentUrl = (paymentId: number,) => {


  

  return `/payments/${paymentId}`
}

export const paymentsControllerGetPayment = async (paymentId: number, options?: RequestInit): Promise<paymentsControllerGetPaymentResponse> => {
  
  return sdkFetch<paymentsControllerGetPaymentResponse>(getPaymentsControllerGetPaymentUrl(paymentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * Read-only internal convenience route for support and admin personas. It filters payment resources by owning userId.
 * @summary Return internal payments for a specific userId
 */
export type paymentsControllerGetUserPaymentsResponse200 = {
  data: Payment[]
  status: 200
}

export type paymentsControllerGetUserPaymentsResponse401 = {
  data: void
  status: 401
}

export type paymentsControllerGetUserPaymentsResponse403 = {
  data: void
  status: 403
}
    
export type paymentsControllerGetUserPaymentsResponseSuccess = (paymentsControllerGetUserPaymentsResponse200) & {
  headers: Headers;
};
export type paymentsControllerGetUserPaymentsResponseError = (paymentsControllerGetUserPaymentsResponse401 | paymentsControllerGetUserPaymentsResponse403) & {
  headers: Headers;
};

export type paymentsControllerGetUserPaymentsResponse = (paymentsControllerGetUserPaymentsResponseSuccess | paymentsControllerGetUserPaymentsResponseError)

export const getPaymentsControllerGetUserPaymentsUrl = (userId: number,) => {


  

  return `/users/${userId}/payments`
}

export const paymentsControllerGetUserPayments = async (userId: number, options?: RequestInit): Promise<paymentsControllerGetUserPaymentsResponse> => {
  
  return sdkFetch<paymentsControllerGetUserPaymentsResponse>(getPaymentsControllerGetUserPaymentsUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



