/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Payments Service
 * Payments service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.2.0
 */
import type {
  HealthCheckResponse,
  Payment
} from './model';


/**
 * @summary Payments service health check
 */
export type healthControllerGetHealthResponse200 = {
  data: HealthCheckResponse
  status: 200
}
    
export type healthControllerGetHealthResponseSuccess = (healthControllerGetHealthResponse200) & {
  headers: Headers;
};
;

export type healthControllerGetHealthResponse = (healthControllerGetHealthResponseSuccess)

export const getHealthControllerGetHealthUrl = () => {


  

  return `http://localhost:3002/health`
}

export const healthControllerGetHealth = async ( options?: RequestInit): Promise<healthControllerGetHealthResponse> => {
  
  const res = await fetch(getHealthControllerGetHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: healthControllerGetHealthResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthControllerGetHealthResponse
}



/**
 * @summary Return a list of all payments
 */
export type paymentsControllerGetPaymentsResponse200 = {
  data: Payment[]
  status: 200
}
    
export type paymentsControllerGetPaymentsResponseSuccess = (paymentsControllerGetPaymentsResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerGetPaymentsResponse = (paymentsControllerGetPaymentsResponseSuccess)

export const getPaymentsControllerGetPaymentsUrl = () => {


  

  return `http://localhost:3002/payments`
}

export const paymentsControllerGetPayments = async ( options?: RequestInit): Promise<paymentsControllerGetPaymentsResponse> => {
  
  const res = await fetch(getPaymentsControllerGetPaymentsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: paymentsControllerGetPaymentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as paymentsControllerGetPaymentsResponse
}



/**
 * @summary Return all payments done by a specific user
 */
export type paymentsControllerGetUserPaymentsResponse200 = {
  data: Payment[]
  status: 200
}
    
export type paymentsControllerGetUserPaymentsResponseSuccess = (paymentsControllerGetUserPaymentsResponse200) & {
  headers: Headers;
};
;

export type paymentsControllerGetUserPaymentsResponse = (paymentsControllerGetUserPaymentsResponseSuccess)

export const getPaymentsControllerGetUserPaymentsUrl = (id: number,) => {


  

  return `http://localhost:3002/payments/${id}`
}

export const paymentsControllerGetUserPayments = async (id: number, options?: RequestInit): Promise<paymentsControllerGetUserPaymentsResponse> => {
  
  const res = await fetch(getPaymentsControllerGetUserPaymentsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: paymentsControllerGetUserPaymentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as paymentsControllerGetUserPaymentsResponse
}



