/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me. support and admin can read the internal /users routes.
 * OpenAPI spec version: 0.4.0
 */
import type { HealthCheckResponseStatus } from './healthCheckResponseStatus';
import type { HealthCheckResponseService } from './healthCheckResponseService';

export interface HealthCheckResponse {
  /** Service status */
  status: HealthCheckResponseStatus;
  /** Service name */
  service: HealthCheckResponseService;
}
