/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Service name
 */
export type HealthCheckResponseService = typeof HealthCheckResponseService[keyof typeof HealthCheckResponseService];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckResponseService = {
  'users-service': 'users-service',
} as const;
