/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me. support and admin can read the internal /users routes.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Service status
 */
export type HealthCheckResponseStatus = typeof HealthCheckResponseStatus[keyof typeof HealthCheckResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckResponseStatus = {
  ok: 'ok',
} as const;
