/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.1.0
 */
import type { HealthCheckResponseStatus } from './healthCheckResponseStatus';
import type { HealthCheckResponseService } from './healthCheckResponseService';

export interface HealthCheckResponse {
  /** Service status */
  status: HealthCheckResponseStatus;
  /** Service name */
  service: HealthCheckResponseService;
}
