/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.1.0
 */

/**
 * Role of the user
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  admin: 'admin',
  manager: 'manager',
  user: 'user',
} as const;
