/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me. support and admin can read the internal /users routes.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Role of the user for authorization decisions
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  customer: 'customer',
  support: 'support',
  admin: 'admin',
} as const;
