/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Users Service
 * Users service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me. support and admin can read the internal /users routes.
 * OpenAPI spec version: 0.4.0
 */
import type { UserRole } from './userRole';

export interface User {
  /** Unique identifier of the user */
  id: number;
  /** First name of the user */
  firstName: string;
  /** Last name of the user */
  lastName: string;
  /** Email address */
  email: string;
  /** Role of the user for authorization decisions */
  role: UserRole;
  /** Whether the user is active */
  isActive: boolean;
  /** Creation timestamp */
  createdAt: string;
}
