/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Payments Service
 * Payments service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me/payments. support and admin can read internal /payments routes and user payment lookups.
 * OpenAPI spec version: 0.4.0
 */

/**
 * Service name
 */
export type HealthCheckResponseService = typeof HealthCheckResponseService[keyof typeof HealthCheckResponseService];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckResponseService = {
  'payments-service': 'payments-service',
} as const;
