/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Payments Service
 * Payments service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.2.0
 */

/**
 * Service status
 */
export type HealthCheckResponseStatus = typeof HealthCheckResponseStatus[keyof typeof HealthCheckResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckResponseStatus = {
  ok: 'ok',
} as const;
