/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Payments Service
 * Payments service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.1.0
 */

export type PaymentMethod = typeof PaymentMethod[keyof typeof PaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethod = {
  credit_card: 'credit_card',
  paypal: 'paypal',
  bank_transfer: 'bank_transfer',
  stripe: 'stripe',
} as const;
