/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Payments Service
 * Payments service API for the genxapi ecosystem demo. Protected routes use a demo HS256 bearer JWT. customer can read only /me/payments. support and admin can read internal /payments routes and user payment lookups.
 * OpenAPI spec version: 0.4.0
 */
import type { PaymentStatus } from './paymentStatus';
import type { PaymentMethod } from './paymentMethod';

export interface Payment {
  /** Unique payment identifier */
  id: number;
  /** Foreign key referencing the user */
  userId: number;
  /** Payment amount */
  amount: number;
  /** ISO currency code */
  currency: string;
  status: PaymentStatus;
  method: PaymentMethod;
  /** External transaction reference */
  transactionId: string;
  createdAt: string;
}
