/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Payments Service
 * Payments service API for the genxapi ecosystem demo
 * OpenAPI spec version: 0.2.0
 */

export type PaymentStatus = typeof PaymentStatus[keyof typeof PaymentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
  refunded: 'refunded',
} as const;
